name: Build and Push C# .NET version 8 Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/build-push-action@v3
      with:
        context: .
        file: dockerfiles/c-sharp/8/Dockerfile
        tags: docker.io/sololaboratories/c-sharp:8
        push: true